### ISSUE TITLE
Mask detailer worklow disappeared  in image refiner

### ISSUE THREAD

**Issue by Rkkss** [ltdrdata/ComfyUI-Workflow-Component#11]
![Untitled](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/127614350/4674ef46-ec7d-4a1f-bd48-ce73d53c6bf6)

this is latest commit

**Comment by ltdrdata** [comment]
This issue is introduced by BOOLEAN support. I'll update soon.

**Comment by ltdrdata** [comment]
NOTICE:

I'm currently in the process of preparing the patch, but it's expected to take around half a day for testing and actual integration into the main version. Until then, as a temporary measure, you can revert to the previous version of the impact pack using the following method.

goto `ComfyUI-Impact-Pack` dir in cmd
and execute `git checkout 0608fb6`

**Comment by Rkkss** [comment]
Is it okay  to update yet.
Also which comfy commit? Last time I updated, it also broke a bunch of nodes

**Comment by ltdrdata** [comment]
> Is it okay to update yet. Also which comfy commit? Last time I updated, it also broke a bunch of nodes

Make sure latest version of `ComfyUI`, `Impact Pack`,  `Workflow Component`.
Now they are working.
