### ISSUE TITLE
Disable LORA dropdown selector

### ISSUE THREAD

**Issue by davidbejarcaceres** [ltdrdata/ComfyUI-Workflow-Component#12]
When I do not want to use any LORA, the dropdown is auto selected.

We need a CheckBox to enable/disable LORA in dropdown, or a "----" as first option in the dropdown.

**Comment by ltdrdata** [comment]
> When I do not want to use any LORA, the dropdown is auto selected.
> 
> We need a CheckBox to enable/disable LORA in dropdown, or a "----" as first option in the dropdown.

CTRL-B on `Load LoRA` node. It will bypass that node.
You need to update to latest version of ComfyUI.

This is a very new feature.
