### ISSUE TITLE
Image Refiner missing components

### ISSUE THREAD

**Issue by Charla224** [ltdrdata/ComfyUI-Workflow-Component#13]
I'm trying to use the image refiner and have only been able to select components a single time. Ever since I restarted comfyui I do not get the list of components.

Not 

![image](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/142271838/6e6c838e-a20e-47bd-9914-555758fb5b7f)

**Comment by ltdrdata** [comment]
Please ensure that your ComfyUI and custom nodes are updated to the latest version.
