### ISSUE TITLE
All nodes in chain triggered from workflow component even when no changes

### ISSUE THREAD

**Issue by thelemuet** [ltdrdata/ComfyUI-Workflow-Component#15]
I've REALLY been wanting to use this but I'm having an issue that I can't figure out if a bug, limitation or user error, hoping for a confirmation.

Is it normal that on every generation it will restart from back up the chain of nodes from the workflow component even when I made no changes to it?

Even the simplest test I made with this component:

![test](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/86247933/fcc06eed-d88a-4954-b234-1a6d8fac3070)

Adding it to my workflow before a kSampler and typing a prompt in it, hitting "Prompt queue" multiple times it will start from that component no matter if it was untouched in-between generations . It will keep generating the same image over and over. No changes anywhere else in the workflow, using fixed seed, etc.

Any idea?

Thanks!

**Comment by ltdrdata** [comment]
The problem has already been identified. It will likely be resolved by tomorrow due to other tasks.

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by thelemuet** [comment]
Thanks for looking into it! Am I assuming correctly the fix has not yet been committed? Last commit is from before this report. Sorry in case I am confused/not understanding.

**Comment by ltdrdata** [comment]
> Thanks for looking into it! Am I assuming correctly the fix has not yet been committed? Last commit is from before this report. Sorry in case I am confused/not understanding.

Oops.. I'd forgot to push...

f92ee9ba59ef16d63c9ac0da2b804d8649ba9fbf

**Comment by thelemuet** [comment]
It's working, thanks!
