### ISSUE TITLE
Node types were not found...

### ISSUE THREAD

**Issue by hightechpresha** [ltdrdata/ComfyUI-Workflow-Component#16]
Hey ltdrdata, 

I watched your video tutorial on the topic: "[ComfyUI Workflow Component - Component Creation Tutorial](https://www.youtube.com/watch?v=JE5B1jsBOvk)". I exported the newly created component using the Export As Component button. When I drag and drop the component into an existing workflow it is also displayed correctly. If I now save the workflow, close Comfyui and start it again, I always get the following error:

![node types-not-found](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/20563696/fac1becc-87dd-43c0-bc86-616c4524565f)

Error: When loading the graph, the following node types were not found:
"## AIO-Advance-KSampler [b8a908]"
Nodes that have failed to load will show as red on the graph.

Where is the error in my walkthrough and how can I fix it?

**Comment by ltdrdata** [comment]
> Hey ltdrdata,
> 
> I watched your video tutorial on the topic: "[ComfyUI Workflow Component - Component Creation Tutorial](https://www.youtube.com/watch?v=JE5B1jsBOvk)". I exported the newly created component using the Export As Component button. When I drag and drop the component into an existing workflow it is also displayed correctly. If I now save the workflow, close Comfyui and start it again, I always get the following error:
> 
> ![node types-not-found](https://user-images.githubusercontent.com/20563696/262452853-fac1becc-87dd-43c0-bc86-616c4524565f.jpg)
> 
> Error: When loading the graph, the following node types were not found: "## AIO-Advance-KSampler [b8a908]" Nodes that have failed to load will show as red on the graph.
> 
> Where is the error in my walkthrough and how can I fix it?

Did you save the workflow as "Save Full" when saving? The difference between "Save" and "Save Full" is whether the components are stored within the workflow itself or not. To load a workflow saved with just "Save," you would need to externally read the components, so the corresponding component file should be located in ComfyUI-Workflow-Component/components.

**Comment by hightechpresha** [comment]
Thanks ltdrdata, 

that was exactly the problem. After saving the workflow via the Save Full button the error did not get anymore.
