### ISSUE TITLE
Issue with Impact Switch in Component flow?

### ISSUE THREAD

**Issue by eanism** [ltdrdata/ComfyUI-Workflow-Component#20]
Attempting to replicate the following logic in a component:
![opt-1](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/73239282/ad1f8072-d643-4b60-983c-9d62e370d9f4)
Using an optional input so the highest index input will always be used (so index 0 if only the required input is supplied, index 1 if the optional input is also supplied):
![opt2](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/73239282/ddfea4df-f007-4b2d-ada6-c70584759180)
Produces the following error:
![opt3](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/73239282/cba63763-3da7-45d0-9bc2-5aa3669c86ff)
Not sure if I'm misusing the nodes (pilot error) of if there's a legitimate issue, and I also wouldn't be surprised if there were a better way of achieving what I'm trying to do, so apologies if the issue is something I'm doing.
Thanks in advance, you're doing amazing work please keep it up!

**Comment by ltdrdata** [comment]
`ImpactSwitch` is not compatible with the Workflow component. As there are ongoing efforts to completely change the current execution model (based on this [PR](https://github.com/comfyanonymous/ComfyUI/pull/931)), this branch will only be maintained to the extent that it does not become completely non-functional, and no additional work is planned for it.
