### ISSUE TITLE
There is no option for Open in Image Refiner in Save Image node

### ISSUE THREAD

**Issue by chrisprojs** [ltdrdata/ComfyUI-Workflow-Component#29]
There is something wrong with it. I can use that tool in Load Image, but there is no option in Save Image nodes
![Screenshot 2023-11-26 192647](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/111422870/bac960ce-81c0-411f-b3e5-f5dbc76b52ec)
![Screenshot 2023-11-26 192700](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/111422870/5f3bfbd9-be73-44aa-b26b-a69ed60d0f76)

**Comment by ltdrdata** [comment]
That's normal. It is meaningless to use Image Refiner in Save Image because it cannot be utilized. Instead of Save Image, use the Preview Bridge from the Impact Pack.
