### ISSUE TITLE
feature request - Multiple inputs of the same type

### ISSUE THREAD

**Issue by whmc76** [ltdrdata/ComfyUI-Workflow-Component#33]
I want to input three different images for processing, but it seems that even if I add three image input nodes, it is still regarded as the same input and will cause an error

got prompt
'🔥 - Failed to save json data.'
'🔥 - Got prompt'
len(prompt): 5
'🔥 - 5 Nodes not included in prompt but is activated'
ERROR:root:Failed to validate prompt for output 6:
ERROR:root:* ## 后处理-合成对比照 [f679bb] 3:
ERROR:root:  - Return type mismatch between linked nodes: image, IMAGE != *
ERROR:root:Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
[profiler] #5 PreviewImage: 0.0 seconds, total 0.0 seconds(#2)
Prompt executed in 0.02 seconds

**Comment by ltdrdata** [comment]
The workflow component is soon to undergo an overhaul based on the `group node` and https://github.com/comfyanonymous/ComfyUI/pull/931.
