### ISSUE TITLE
warning message started to appear after updating the Derfuu_ComfyUI_ModdedNodes nodes. 

### ISSUE THREAD

**Issue by cjps-br** [ltdrdata/ComfyUI-Workflow-Component#37]
a warning message started to appear after updating the Derfuu_ComfyUI_ModdedNodes nodes. 

The message is: "[Workflow-Component] '## sdxl-ksample [3c7e70]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###)"

So I edited the sdxl-ksample.component.json component, modifying the nodes that were considered missing and now the message is no longer appearing. I attach the component that I modified to be reviewed, evaluated and perhaps to replace the current node.

[sdxl-ksample.component.json](https://github.com/ltdrdata/ComfyUI-Workflow-Component/files/15119683/sdxl-ksample.component.json)

**Comment by ltdrdata** [comment]
Since the Workflow Component plans to perform an overhaul based on group nodes, the current version is not being maintained.

The default component in the repo have been replaced with your component.
