### ISSUE TITLE
 [Workflow-Component] '## sdxl-ksample [3c7e70]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###) 

### ISSUE THREAD

**Issue by Creative-comfyUI** [ltdrdata/ComfyUI-Workflow-Component#40]
Hello, 

I made the update without any success. 

Thanks

**Comment by ltdrdata** [comment]
It means you didn't update this custom node properly.

You cannot update this custom node in ComfyUI-Manager if it is set as default channel.

If you don't know how to update it. 
Then, ust goto `ComfyUI/custom_nodes/ComfyUI-Workflow-Component` in cmd. 
And execute `git pull`.

Execute `git reset --hard && git pull` if error occurs during then.

**Comment by Creative-comfyUI** [comment]
Thank you for your answer. I updated using the developper mode in comfyUI. 

As I am on mac I presume I have to go on terminal and made a git clone. Am I right ?

**Comment by ltdrdata** [comment]
> Thank you for your answer. I updated using the developper mode in comfyUI.
> 
> As I am on mac I presume I have to go on terminal and made a git clone. Am I right ?

Yeah.. But you have to `git pull` not `git clone`.

**Comment by Creative-comfyUI** [comment]
Thanks. I think the component is not installed. Should I have a new git  pull ? 

remote: Enumerating objects: 1100, done.
remote: Counting objects: 100% (450/450), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 1100 (delta 348), reused 387 (delta 301), pack-reused 650
Receiving objects: 100% (1100/1100), 6.49 MiB | 7.47 MiB/s, done.
Resolving deltas: 100% (730/730), done.
From https://github.com/ltdrdata/ComfyUI-Workflow-Component
 * branch            HEAD       -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.

**Comment by ltdrdata** [comment]
> Thanks. I think the component is not installed. Should I have a new git pull ?
> 
> remote: Enumerating objects: 1100, done. remote: Counting objects: 100% (450/450), done. remote: Compressing objects: 100% (149/149), done. remote: Total 1100 (delta 348), reused 387 (delta 301), pack-reused 650 Receiving objects: 100% (1100/1100), 6.49 MiB | 7.47 MiB/s, done. Resolving deltas: 100% (730/730), done. From https://github.com/ltdrdata/ComfyUI-Workflow-Component
> 
> * branch            HEAD       -> FETCH_HEAD
>   hint: You have divergent branches and need to specify how to reconcile them.
>   hint: You can do so by running one of the following commands sometime before
>   hint: your next pull:
>   hint:
>   hint:   git config pull.rebase false  # merge
>   hint:   git config pull.rebase true   # rebase
>   hint:   git config pull.ff only       # fast-forward only
>   hint:
>   hint: You can replace "git config" with "git config --global" to set a default
>   hint: preference for all repositories. You can also pass --rebase, --no-rebase,
>   hint: or --ff-only on the command line to override the configured default per
>   hint: invocation.

`git pull` again. If it doesn't work. Remove it and reinstall.

**Comment by Creative-comfyUI** [comment]
Thanks. When you say remove it you mean  I delete the  workflow component folder and use git clone ?   With pull I have the error this time. 

From https://github.com/ltdrdata/ComfyUI-Workflow-Component
 * branch            HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories

**Comment by ltdrdata** [comment]
> Thanks. When you say remove it you mean I delete the workflow component folder and use git clone ? With pull I have the error this time.
> 
> From https://github.com/ltdrdata/ComfyUI-Workflow-Component
> 
> * branch            HEAD       -> FETCH_HEAD
>   fatal: refusing to merge unrelated histories

Yup.. you need to delete that dir and git clone again.
I don't know why but your ComfyUI-Workflow-Component dir is unmatched with this repo.

**Comment by Creative-comfyUI** [comment]
Many Thanks, it works. No more errors. 

Even if it is not the place to ask a question about Ksampler (inspire), if whish to know if it is possible to have no variation batch seed mode? I mean 0 instead of 0.1. Do you know how the variation of the seed is calculated? The seed is the one of the first image and for the other images there is x% noise injection coming from the sampler except for euler and DDim. is it a way to know what is this percentage and how is it calculate to have the seed of the images that follow the first image?

**Comment by ltdrdata** [comment]
> Many Thanks, it works. No more errors.
> 
> Even if it is not the place to ask a question about Ksampler (inspire), if whish to know if it is possible to have no variation batch seed mode? I mean 0 instead of 0.1. Do you know how the variation of the seed is calculated? The seed is the one of the first image and for the other images there is x% noise injection coming from the sampler except for euler and DDim. is it a way to know what is this percentage and how is it calculate to have the seed of the images that follow the first image?

https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/34de5e338f4cbe0d801dd175e9d086271b97a7c8/inspire/libs/utils.py#L65C1-L70C57

That is the logic of the variation_seed.

**Comment by Gloynus** [comment]
Hi. I did the same thing (deleted the folder and git clone), the old error went away, but it was replaced by a lot more errors.

```
[Workflow-Component] '## face-detailer-start [f6484f]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "FaceDetailerPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "FaceDetailerPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## face-detailer-start [f6484f]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "FaceDetailerPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "FaceDetailerPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## mask-detailer.2lora.ir [a56996]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## mask-detailer.2lora.ir [a56996]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## mask-detailer.ir [0ff698]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## mask-detailer.ir [0ff698]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## mask-detailer.lora.ir [a745ba]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## mask-detailer.lora.ir [a745ba]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "DetailerForEachDebugPipe" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## pixel-upscale-basic_pipe [286ed5]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "LatentPixelScale" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "LatentPixelScale" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## pixel-upscale-basic_pipe [286ed5]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "LatentPixelScale" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "LatentPixelScale" node is not installed. Please install that node through ComfyUI-Mananger. ###
```
