### ISSUE TITLE
some functional suggestions

### ISSUE THREAD

**Issue by LPG-VERSION** [ltdrdata/ComfyUI-Workflow-Component#44]
Can you provide a batch renaming function? Adding numbering to titles and renaming slot names are time-consuming tasks, and currently there are no specific rules for titles and classification widgets/inputs/outputs, which makes using this extension very time-consuming. I have to define my own set of rules to solve this problem.
The classification and naming convention of input/output/widgets that I have defined myself:
![image](https://github.com/user-attachments/assets/b3ca74e0-77be-4458-960b-09a07043b045)
![image](https://github.com/user-attachments/assets/a59dd750-85ab-4bd0-8924-2e3f5ec62d7c)

**Comment by ltdrdata** [comment]
The workflow component will be completely reworked.
It is recommended not to apply it except for experimental work.

**Comment by LPG-VERSION** [comment]
> The workflow component will be completely reworked. It is recommended not to apply it except for experimental work.

Okay, I took some time to understand the Comfyui extension and designed a naming extension that fits my own rules, but now it seems unnecessary and I look forward to a brand new custom component design
