### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'node_errors')

### ISSUE THREAD

**Issue by seanphan** [ltdrdata/ComfyUI-Workflow-Component#6]
Problem: Upon enable Workflow component with Comfy UI I got this error even running with workflow from ComfyUI Example repo.
Also the seed number won't random after each generation.

Solution: Remove Workflow component by install a clean version of Comfy UI. Hope this can give you some clue to address this issue.

![image](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/5804000/6683eaf9-bdb2-45e3-a78c-6ef0221087e2)
![image](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/5804000/fd347d13-d5b4-4ed7-ad41-4e8f1c559a74)
![image](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/5804000/1b4f5911-b545-4a04-8883-d71208ec4508)

**Comment by ltdrdata** [comment]
Did you updated to latest version?
I'd patched this 2 days ago.

ps. I just checked your stack trace. The code line is mis-aligned. You are on old version definitely.
Update and try again.

**Comment by seanphan** [comment]
Thank you, it has been fixed
